apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: front-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: 05-project.narumir.io
    http:
      paths:
      - backend:
          service:
            name: frontend
            port:
              number: 3000
        path: /
        pathType: Prefix
  tls:
    - hosts:
        - 05-project.narumir.io
      secretName: letsencrypt