apiVersion: v1
kind: ConfigMap
metadata:
  name: front-configmap
  namespace: frontend
data:
  NEXT_PUBLIC_API_URL: https://api.05-project.narumir.io
  NEXT_PUBLIC_NAVER_CLIENT_ID: D1sa9szPKoZZ87nZeCiP
  NEXT_PUBLIC_NAVER_REDIRECT_URL: https://api.05-project.narumir.io/api/v1/auth/naver/callback
  NEXT_PUBLIC_KAKAO_CLIENT_ID: d702fab7a1e36e8bc5959c1faac17b11
  NEXT_PUBLIC_KAKAO_REDIRECT_URL: https://api.05-project.narumir.io/api/v1/auth/kakao/callback
  NEXT_PUBLIC_GOOGLE_CLIENT_ID: 44860597251-jscuuflrss4kk3noodu87pfe1qa8hbur.apps.googleusercontent.com
  NEXT_PUBLIC_GOOGLE_REDIRECT_URL: https://api.05-project.narumir.io/api/v1/auth/google/callback
