apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deploy
  labels:
    app: front-deploy
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavilable: 1
      maxSurge: 1
  minReadySeconds: 20
  replicas: 3
  selector:
    matchLabels:
      app: front-deploy
  template:
    metadata:
      labels:
        app: front-deploy
    spec:
      containers:
      - image: ghcr.io/05-project/05-project-client
        name: frontend-app
        port:
        - containerPort: 8080