apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend                   
  minReplicas: 2                    
  maxReplicas: 20                   
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60      
  behavior:
    scaleDown:
      policies:
      - type: Pods
        value: 1                   
        periodSeconds: 60          
      stabilizationWindowSeconds: 300 
    scaleUp:
      policies:
      - type: Pods
        value: 2                   
        periodSeconds: 30          
      stabilizationWindowSeconds: 300 
