apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend                   # 대상 Deployment 이름
  minReplicas: 2                    # 최소 Pod 수
  maxReplicas: 20                   # 최대 Pod 수
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60      # CPU 사용률 60% 이상일 때 스케일 업
  behavior:
    scaleDown:
      policies:
      - type: Pods
        value: 1                   # 한 번에 줄일 Pod 수
        periodSeconds: 60          # 스케일다운 간격 (1분)
      stabilizationWindowSeconds: 300 # 안정화 창 (5분 동안 스케일다운 제한)
    scaleUp:
      policies:
      - type: Pods
        value: 2                   # 한 번에 늘릴 Pod 수
        periodSeconds: 30          # 스케일업 간격 (30초)
      stabilizationWindowSeconds: 300 # 안정화 창 (5분 동안 스케일업 제한)
