apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: backend-cert
  namespace: backend
spec:
  secretName: letsencrypt
  dnsNames:
    - api.05-project.narumir.io
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: backend
spec:
  ingressClassName: nginx
  rules:
    - host: api.05-project.narumir.io
      http:
        paths:
          - backend:
              service:
                name: api-server
                port:
                  number: 4000
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - api.05-project.narumir.io
      secretName: letsencrypt
