apiVersion: v1
kind: PersistentVolume
metadata:
  name: argocd-repo-server-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  awsElasticBlockStore:
    volumeID: vol-0019ded636c3fbf70
    fsType: ext4
